services:
  app:
    build: .
    container_name: resasalles_app
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    command: bash -lc "until nc -z ${DB_HOST} ${DB_PORT}; do echo 'En attente de MySQL...'; sleep 2; done; php public/index.php setup && apache2-foreground"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: resasalles_db
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
